var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/custom-api/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qkfnjh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bw_x_7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0hoaxo_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gkwk1-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1e_rldm._.js")
R.c("server/chunks/ssr/_1yxiorf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_services_custom-api_page_actions_02fyu80.js")
R.m(28895)
module.exports=R.m(28895).exports
